services:
  flask_pysaml2_example:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    entrypoint: ["uv", "run", "gunicorn", "--bind", "0.0.0.0:5000", "flask_pysaml2_example:create_app()"]
